<!DOCTYPE HTML>
<html>	
<head>
<meta http-equiv="Content-Type" content="text/html; charset=GBK">  
<title> Highcharts + Ajax + Servlet Demo </title>  
<script type="text/javascript" src="http://cdn.hcharts.cn/jquery/jquery-1.8.3.min.js"></script>
<script src="/static/bootstrap/js/highcharts.js"></script>

<script type="text/javascript">  
$(function() {
    $(document).ready(function() {
        Highcharts.setOptions({
            global: {
                useUTC: false
            }
        });
        var chart;
        chart = new Highcharts.Chart({
            chart: {
                renderTo: 'container5',
                type: 'spline',
                animation: Highcharts.svg,
                // don't animate in old IE               
                marginRight: 10,
                events: {
                    load: function() {}
                }
            },
            title: {
                text: 'Live random data'
            },
            xAxis: {
                type: 'datetime',
                tickPixelInterval: 150
            },
            yAxis: [{
                title: {
                    text: 'Value'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            {
                title: {
                    text: 'Name'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            }],
            tooltip: {
                formatter: function() {
                    return '<b>' + this.series.name + '</b><br/>' + Highcharts.dateFormat('%Y-%m-%d %H:%M:%S', this.x) + '<br/>' + Highcharts.numberFormat(this.y, 2);
                }
            },
            legend: {
                enabled: false
            },
            exporting: {
                enabled: false
            },
            series: [{
                name: 'Random data',
                data: (function() { // generate an array of random data                             
                    var data = [],
                    time = (new Date()).getTime(),
                    i;
                    for (i = -19; i <= 0; i++) {
                        data.push({
                            x: time + i * 1000,
                            y: Math.random()
                        });
                    }
                    return data;
                })()
            },
            {
                name: 'Random data',
                data: (function() { // generate an array of random data                             
                    var data = [],
                    time = (new Date()).getTime(),
                    i;
                    for (i = -19; i <= 0; i++) {
                        data.push({
                            x: time + i * 1000,
                            y: Math.random()
                        });
                    }
                    return data;
                })()
            }]
        }); // set up the updating of the chart each second                     
        var series = chart.series[0];
        var series1 = chart.series[1];
        setInterval(function() {
            var x = (new Date()).getTime(),
            // current time         
            y = Math.random();
            series.addPoint([x, y + 1], true, true);
            series1.addPoint([x, y - 1], true, true);
        },
        1000);
    });
});
        </script>  
        <style>  
            html,body { margin:0px; height:100%; }  
        </style>  
    </head>  
      
    <body>  
        <div id="container5" style="min-width: 400px; height: 80%; margin: 0 auto">  
        </div>  
    </body>  
<html>



</html>
